
###
POST http://127.0.0.1:8080/customer
Content-Type: application/json

{
  "id": 0,
  "firstName": "John",
  "lastName": "Smith",
  "email": "john.smith@company.com"
}

###
PATCH http://127.0.0.1:8080/customer/1
Content-Type: application/json

{
  "id": 3,
  "firstName": "Tony",
  "lastName": "Kazanjian",
  "email": "tony@email.com "
}

###
GET http://127.0.0.1:8080/customer
Accept: application/json

###
GET http://127.0.0.1:8080/customer/3
Accept: application/json

###
DELETE http://127.0.0.1:8080/customer/2

